### ISSUE TITLE
[BUG] QApplication: invalid style override passed, ignoring it.

### ISSUE THREAD

**Issue by Kazzz-S** [Kazzz-S/klayout#15]
@klayoutmatthias

Style options passed to QApplication are ignored.
This worked up to version 0.24.10.

```
MacBookPro(1)$ ./klayout -v
KLayout 0.25

MacBookPro(2)$ ./klayout -e -style=motif
Warning: QApplication: invalid style override passed, ignoring it.
```
The "-e" option is accepted and KLayout starts in the editor mode.

**Comment by klayoutmatthias** [comment]
Please also assign this to me.

Thanks,

Matthias

**Comment by Kazzz-S** [comment]
Assigned to Matthias as https://github.com/klayoutmatthias/klayout/issues/52
