### ISSUE TITLE
[BUG] "About klayout" strings do not fit in the dialog window

### ISSUE THREAD

**Issue by Kazzz-S** [Kazzz-S/klayout#16]
@klayoutmatthias

![about-1](https://user-images.githubusercontent.com/16847255/34472560-2887202c-efa8-11e7-9d24-94c0cd059ddd.png)

If I stretch the window border, they can be seen.
![about-2](https://user-images.githubusercontent.com/16847255/34472562-2dcedf7a-efa8-11e7-9c3c-0d871abef8a6.png)

**Comment by klayoutmatthias** [comment]
Please assign this to me, if this is possible.

**Comment by Kazzz-S** [comment]
Assigned to Matthias as https://github.com/klayoutmatthias/klayout/issues/53
