### ISSUE TITLE
[BUG] Blurred image in the main canvas

### ISSUE THREAD

**Issue by Kazzz-S** [Kazzz-S/klayout#17]
@klayoutmatthias

**KLayout 0.24.10:**
![klayout-02410](https://user-images.githubusercontent.com/16847255/34472641-bb90aa86-efa9-11e7-8b5b-ffa3e3fb5fde.png)

**KLayout 0.25:**  Partially transparent to the backgroud
![klayout-025](https://user-images.githubusercontent.com/16847255/34472615-22cb8884-efa9-11e7-90e9-b66cee6202c9.png)

**Comment by klayoutmatthias** [comment]
Weired ... could this be a Qt 5 issue?

I don't see this effect on my VirtualBox, but maybe because most of the fancy graphics gimmicks are disabled.

**Comment by Kazzz-S** [comment]
Assigned to Matthias as https://github.com/klayoutmatthias/klayout/issues/55

**Comment by Kazzz-S** [comment]
Refer to  klayoutmatthias#55

This was the issue with Qt 5.10.0. 
Use Qt 5.9.3 as workaround.
