### ISSUE TITLE
Build "pymod" on Yosemite

### ISSUE THREAD

**Issue by Kazzz-S** [Kazzz-S/klayout#28]
Attempt to build the latest (as of July 16, 2018) code on Yosemite, too.

----
Got a compile error:
```
../../../src/tl/tl/tlTimer.cc:48:18: error: use of undeclared identifier 'CLOCK_REALTIME'
  clock_gettime (CLOCK_REALTIME, &spec);
                 ^
../../../src/tl/tl/tlTimer.cc:80:18: error: use of undeclared identifier 'CLOCK_REALTIME'
  clock_gettime (CLOCK_REALTIME, &spec);
                 ^
2 errors generated.
make[2]: *** [tlTimer.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [sub-tl-make_first] Error 2
make: *** [sub-tl-make_first] Error 2
```
because: clock_gettime() is not implemented on older versions of OS X (< 10.12).

----

**Comment by Kazzz-S** [comment]
**[Save As] dialog in 0.25.3**

![2018-07-17 19 09 32](https://user-images.githubusercontent.com/16847255/42811267-15bb451c-89f5-11e8-9e67-bcee8a5c7c47.png)

----
**[Save As] dialog in 0.26**

![2018-07-17 19 08 01](https://user-images.githubusercontent.com/16847255/42811335-44f8f428-89f5-11e8-857d-a5cd776fcff0.png)

**Comment by dwang** [comment]
Hi Kazzz,

I experienced the same compilation issue you had. I fixed the error in my pull request [here](https://github.com/klayoutmatthias/klayout/pull/145).

Regards,
Daniel

**Comment by Kazzz-S** [comment]
@dwang 

Hi Daniel,

Thanks for your comment. 
I've already found a workaround as above and compiling went through. 
Now going to build on HighSierra, too.

By the way, have you experienced the "Save As" dialog issue above in your environment (El Capitan, I guess)?
In fact, I got this when trying to save a design (with just one box) as OASIS.

Regards,
Kazzz

**Comment by Kazzz-S** [comment]
Merged https://github.com/klayoutmatthias/klayout/pull/145

Thanks!
Kazzz

**Comment by Kazzz-S** [comment]
(1) **[Save As] dialog in 0.25.3**

![2018-07-17 19 09 32](https://user-images.githubusercontent.com/16847255/42811267-15bb451c-89f5-11e8-9e67-bcee8a5c7c47.png)

----
(2) **[Save As] dialog in 0.26 of _pymod branch_: both in Yosemite and HighSierra.**
**_master branch_ does not have this issue.**

![2018-07-17 19 08 01](https://user-images.githubusercontent.com/16847255/42811335-44f8f428-89f5-11e8-857d-a5cd776fcff0.png)
![2018-07-21 16 09 44](https://user-images.githubusercontent.com/16847255/43033203-fc6dd250-8d00-11e8-86e2-0668e18a2618.png)

**If forced to save as GDS2**
![2018-07-22 12 30 59](https://user-images.githubusercontent.com/16847255/43043157-bfce727e-8dc7-11e8-948c-8d3cc78f1104.png)
![2018-07-22 8 36 11](https://user-images.githubusercontent.com/16847255/43043158-c1cb6bae-8dc7-11e8-8c45-27302f265a20.png)
